### ISSUE TITLE
error at start of runs, maybe related to cofig?

### ISSUE THREAD

**Issue by nfkruska** [ncsu-landscape-dynamics/rpops#102]
```
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in (function (x)  : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in (function (x)  : attempt to apply non-function
```

I get a handful of these errors when using the validate and calibrate functions. I haven't had time to really explore any common factors that cause this (e.g. source data). But maybe someone more familiar with the base code will recognize what's happening. I'm using the most recent main branch.

**Comment by ChrisJones687** [comment]
Yes, this is coming from the data handling internally. See [rspatial/terra#30](https://github.com/rspatial/terra/issues/30).

**Comment by nfkruska** [comment]
Ah, good to know. I was coming back to note that it didn't stop the process. I'll close it for now.
