### ISSUE TITLE
Write out all_simulations from multirun

### ISSUE THREAD

**Issue by nfkruska** [ncsu-landscape-dynamics/rpops#117]
The options given for `pops_multirun` `write_outputs` parameter are given as: "none", "summary outputs" or "all simulations".

"all simulations" is variously written as "all_simulations" or "all simulations" with or without an underscore. The accepted argument is with the underscore. This is inconsistent with the "summary outputs" argument that does not have an underscore. See here:

https://github.com/ncsu-landscape-dynamics/rpops/blob/41ffc172220083c46a2e0fa66e0065c0f19ef8a3/R/configuration.R#L81

Additionally, although "all_simulations" is an accepted argument, it currently functions identically to "summary outputs". See here:

https://github.com/ncsu-landscape-dynamics/rpops/blob/41ffc172220083c46a2e0fa66e0065c0f19ef8a3/R/pops_multirun.R#L633

**Comment by ChrisJones687** [comment]
Thanks for pointing out the inconsistency. I meant to add in the documentation that the all_simulations option was a placeholder for future development.

**Comment by nfkruska** [comment]
Roger.
