### ISSUE TITLE
Outputs spatially incomplete under certain scenarios.

### ISSUE THREAD

**Issue by ChrisJones687** [ncsu-landscape-dynamics/rpops#119]
Coming from #116. Need to determine when and why this occurs.

**Comment by nfkruska** [comment]
This still appears to be an issue that I can't track down the cause. I have put a new test folder with 1000m data for you in the SOD_CA shared data drive and updated the multirun code on my NCSU repo to test.

**Comment by ChrisJones687** [comment]
I will take a look and see if I can duplicate this and see where it is happening.
