### ISSUE TITLE
Model runs but only returns exposed

### ISSUE THREAD

**Issue by ChrisJones687** [ncsu-landscape-dynamics/rpops#25]
When running the model using timestep of days, yearly outputs, the model returned exposed but not other metrics. 2 problem spots come to mind 

- [x]  export statement in pops_model function

- [x]  scheduler functionality

Here is the example code that doesn't work it is in abc calibration but the issue is calling the pops_model function.
'''
infected_years_file <- ffIn("purelines_7weeks.tif")
number_of_observations <- 68    ### This is the number of infected cells - just make sure it's consistent across years 
prior_number_of_observations <- 0
prior_means <- c(0, 0, 0, 0, 0, 0)    ### leave as 0 for now, means that you are giving them no weight
prior_cov_matrix <- matrix(ncol = 6, nrow = 6, 0)
params_to_estimate <- c(T, T, T, T, F, F)  ### 1st: reproductive rates, 2nd: natural distance, 3rd: percent natural, 4tH: anthropogenic distance, 5th Natural Kappa, 6th anthropogenic kappa
number_of_generations <- 6
generation_size <- 50
checks = c(60, 20000, 1000, 10000)   
infected_file <- ffIn("Pure_infected.tif")
host_file <- ffIn("Pure_host.tif")
total_plants_file <- ffIn("Pure_host.tif")
temp <- FALSE
temperature_coefficient_file <- ""
precip <- FALSE
precipitation_coefficient_file <- ""
model_type = "SEI"
latency_period = 14
time_step <- "day"
season_month_start <- 1
season_month_end <- 12
start_date <- '2003-01-01'
end_date <- '2003-02-13'
use_lethal_temperature <- FALSE
temperature_file <- ""
lethal_temperature <- -30
lethal_temperature_month <- 1
mortality_on <- FALSE
mortality_rate <- 0
mortality_time_lag <- 0
management <- FALSE
treatment_dates <- c('2003-01-24')
treatments_file <- ""
treatment_method <- "ratio"
natural_kernel_type <- "cauchy"
anthropogenic_kernel_type <- "cauchy"
natural_dir <- "N"
natural_kappa <- 0
anthropogenic_dir <- "NONE"
anthropogenic_kappa <- 0
pesticide_duration <- c(0)
pesticide_efficacy <- 1.0
mask <- NULL
success_metric <- "residual error"  ### keep this the same
output_frequency <- "year"
movements_file = ""  ## ignore - for pigs
use_movements = FALSE
percent_natural_dispersal <- 1.0
anthropogenic_distance_scale <- 0.0
'''

**Comment by ChrisJones687** [comment]
Further testing reveals that this is only a problem when output_frequency is "year" and end_date does not equal "12-31-YYYY"

**Comment by petrasovaa** [comment]
If I understand this correctly, that doesn't sound like a bug, that's how the scheduler works. In r.pops.spread we do have 2 types of outputs, e.g. probability= and probability_series= where the series would use the output frequency and the other would be written out at the end of the simulation.

**Comment by wenzeslaus** [comment]
Does https://github.com/ncsu-landscape-dynamics/pops-core/pull/64 fix this?

**Comment by ChrisJones687** [comment]
It should I was planning to close this once I add the tests from #33 which will contain an automated test to test for outputs with all combinations of time step and output frequency.

**Comment by wenzeslaus** [comment]
Well, that's of course ideal!
