### ISSUE TITLE
latest/dev PoPS version fails to install with CRAN version of terra

### ISSUE THREAD

**Issue by nfkruska** [ncsu-landscape-dynamics/rpops#98]
With a fresh dev version install of PoPS, (e.g. `devtools::install_github("ncsu-landscape-dynamics/rpops")` it will install terra 1.1-4 from CRAN if terra is not already installed. However, the dev version of PoPS now depended on a version of terra (1.1.7) only on github.

If terra was originally installed from github, it will prompt to update. If terra was originally installed from CRAN, the latest version of PoPS will fail to install. You can of course manually update terra from github, but I don't believe this is the desired behavior.

**Comment by ChrisJones687** [comment]
Agreed not desired but what we are stuck with until version 1.1-7 is on CRAN. Some of the functionality that we use is only available in 1.1-7 and above. Installing terra from CRAN is part of the installation instructions in the readme until 1.1-7 is on the CRAN. Going to leave this open until then.

**Comment by nfkruska** [comment]
Ha, yeah  after I posted this I saw you had updated the README to include the need to install terra from github now.
